const SB_URL='https://gkyeujvltxbjlzoxpmtu.supabase.co',SB_KEY='sb_publishable_832zvgEU6KbbVKN_B86UxA_kOuGtih_';const sb=supabase.createClient(SB_URL,SB_KEY);let me=null,shipments=[];const $=x=>document.getElementById(x),now=()=>new Date().toISOString();
async function login(){const {data,error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});$('msg').textContent=error?error.message:'';if(data?.user)loadApp(data.user)}
async function loadApp(u){const {data,error}=await sb.from('profiles').select('*').eq('id',u.id).single();if(error||!data||!data.active)return $('msg').textContent='Usuario sin perfil activo';me=data;$('login').classList.add('hide');$('app').classList.remove('hide');$('who').textContent=me.full_name||u.email;$('role').textContent=me.role;if(['RECEPCION','ADMIN'].includes(me.role))$('newbox').classList.remove('hide');if(me.role==='ADMIN'){$('adminbox').classList.remove('hide');loadUsers()}await refresh();sb.channel('live').on('postgres_changes',{event:'*',schema:'public',table:'shipments'},refresh).subscribe()}
async function refresh(){const {data}=await sb.from('shipments').select('*').order('requested_at',{ascending:false});shipments=data||[];render()}
function esc(x){return String(x||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function label(s){return ({SOLICITADO:'Solicitado',LOCALIZANDO:'Localizando',PREPARADO:'Preparado',PENDIENTE_RECEPCION:'Pendiente de confirmar recepción',EN_RECEPCION:'En Recepción',ENTREGADO:'Entregado',INCIDENCIA:'Incidencia'})[s]||s}
function render(){const q=$('search').value.trim().toLowerCase();const filtered=shipments.filter(s=>[s.tracking,s.customer_name,s.package_location,s.recipient_name,s.recipient_id,s.status,s.notes].some(v=>(v||'').toLowerCase().includes(q)));$('resultcount').textContent=filtered.length+' envío(s) encontrado(s)';$('rows').innerHTML=filtered.map(s=>{let a='';if(['ESTACIONADOS','ADMIN'].includes(me.role)&&['SOLICITADO','LOCALIZANDO','PREPARADO','INCIDENCIA'].includes(s.status))a+='<button onclick="handoff(\''+s.id+'\')">Entregar a Recepción</button>';if(['RECEPCION','ADMIN'].includes(me.role)&&s.status==='PENDIENTE_RECEPCION')a+='<button onclick="confirmReception(\''+s.id+'\')">Confirmar recibido</button>';if(['RECEPCION','ADMIN'].includes(me.role)&&s.status==='EN_RECEPCION')a+='<button onclick="deliver(\''+s.id+'\')">Entrega final</button>';return '<tr><td><b>'+esc(s.tracking)+'</b></td><td>'+esc(s.customer_name)+'</td><td>'+esc(s.package_location)+'</td><td class="badge">'+esc(label(s.status))+'</td><td><div class="actions">'+a+'</div></td></tr>'}).join('')}
async function event(id,type,detail=''){await sb.from('events').insert({shipment_id:id,actor_id:me.id,event_type:type,detail})}
async function createShipment(){const o={tracking:$('tracking').value.trim(),customer_name:$('customer').value.trim(),package_location:$('location').value.trim(),notes:$('notes').value.trim(),requested_by:me.id};if(!o.tracking||!o.customer_name||!o.package_location)return alert('Completa número de envío, cliente y ubicación.');const {data,error}=await sb.from('shipments').insert(o).select().single();if(error)return alert(error.message);await event(data.id,'SOLICITUD_CREADA','Solicitud registrada');['tracking','customer','location','notes'].forEach(x=>$(x).value='');refresh()}
async function createBulk(){const lines=$('bulk').value.split(/\n/).map(x=>x.trim()).filter(Boolean);if(!lines.length)return alert('Introduce al menos una solicitud.');const rows=[];for(const line of lines){const p=line.split(';').map(x=>x.trim());if(p.length<3||!p[0]||!p[1]||!p[2])return alert('Formato incorrecto: '+line+'\nUsa: Nº ENVÍO ; CLIENTE ; UBICACIÓN ; OBSERVACIONES');rows.push({tracking:p[0],customer_name:p[1],package_location:p[2],notes:p.slice(3).join('; '),requested_by:me.id})}const {data,error}=await sb.from('shipments').insert(rows).select();if(error)return alert(error.message);for(const s of data)await event(s.id,'SOLICITUD_CREADA','Solicitud registrada en lote');$('bulk').value='';alert(data.length+' solicitudes registradas correctamente.');refresh()}
async function handoff(id){if(!confirm('¿Confirmas que Estacionados entrega físicamente este envío a Recepción?'))return;const {error}=await sb.from('shipments').update({status:'PENDIENTE_RECEPCION',warehouse_by:me.id,warehouse_at:now(),handoff_at:now()}).eq('id',id);if(error)return alert(error.message);await event(id,'ENTREGADO_POR_ESTACIONADOS','Pendiente de confirmación de Recepción');refresh()}
async function confirmReception(id){if(!confirm('¿Confirmas que Recepción ha recibido físicamente este envío?'))return;const {error}=await sb.from('shipments').update({status:'EN_RECEPCION',reception_by:me.id,reception_at:now(),reception_confirmed_at:now()}).eq('id',id);if(error)return alert(error.message);await event(id,'RECIBIDO_EN_RECEPCION','Recepción confirma la custodia');refresh()}
async function deliver(id){const n=prompt('Nombre de la persona que recoge:');if(!n)return;const dni=prompt('DNI/identificación (opcional):')||'';if(!confirm('¿Confirmas la entrega final a '+n+'?'))return;const {error}=await sb.from('shipments').update({status:'ENTREGADO',recipient_name:n,recipient_id:dni,delivered_by:me.id,delivered_at:now()}).eq('id',id);if(error)return alert(error.message);await event(id,'ENTREGA_FINAL','Entregado a '+n+(dni?' · ID '+dni:''));refresh()}
async function adminCall(body){const {data:{session}}=await sb.auth.getSession();const r=await fetch(SB_URL+'/functions/v1/admin-users',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token,'apikey':SB_KEY},body:JSON.stringify(body)});return await r.json()}
async function createUser(){const b={action:'create',full_name:$('ufull').value.trim(),email:$('uemail').value.trim(),password:$('upass').value,role:$('urole').value};if(!b.full_name||!b.email||b.password.length<8)return alert('Completa nombre, correo y contraseña temporal de al menos 8 caracteres.');const x=await adminCall(b);if(x.error)return alert(x.error);alert('Usuario creado correctamente.');$('ufull').value=$('uemail').value=$('upass').value='';loadUsers()}
async function loadUsers(){const x=await adminCall({action:'list'});if(x.error)return;$('users').innerHTML='<h3>Usuarios</h3><div style="overflow:auto"><table><tr><th>Nombre</th><th>Rol</th><th>Activo</th></tr>'+x.data.map(u=>'<tr><td>'+esc(u.full_name)+'</td><td>'+esc(u.role)+'</td><td>'+(u.active?'Sí':'No')+'</td></tr>').join('')+'</table></div>'}
async function changePassword(){const p=$('newpass').value;if(p.length<8)return alert('Mínimo 8 caracteres.');const {error}=await sb.auth.updateUser({password:p});alert(error?error.message:'Contraseña cambiada correctamente.');$('newpass').value=''}
async function logout(){await sb.auth.signOut();location.reload()}sb.auth.getSession().then(({data})=>{if(data.session)loadApp(data.session.user)});