const SB_URL='https://gkyeujvltxbjlzoxpmtu.supabase.co',SB_KEY='sb_publishable_832zvgEU6KbbVKN_B86UxA_kOuGtih_';const sb=supabase.createClient(SB_URL,SB_KEY);let me=null,shipments=[],events=[],incs=[];const $=x=>document.getElementById(x),now=()=>new Date().toISOString(),esc=x=>String(x||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={SOLICITADO:'Solicitado',LOCALIZANDO:'Localizando',PREPARADO:'Preparado',PENDIENTE_RECEPCION:'Pendiente Recepción',EN_RECEPCION:'En Recepción',ENTREGADO:'Entregado',INCIDENCIA:'Incidencia'};
function go(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(v).classList.add('active');$('title').textContent={dashboard:'Panel de control',new:'Registrar solicitudes',shipments:'Buscador y expedientes',incidents:'Incidencias',admin:'Administración',account:'Mi cuenta'}[v];if(v==='shipments')render();if(v==='incidents')renderIncidents();if(v==='admin')loadUsers()}
async function login(){const {data,error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});$('msg').textContent=error?error.message:'';if(data?.user)loadApp(data.user)}
async function loadApp(u){const {data}=await sb.from('profiles').select('*').eq('id',u.id).single();if(!data?.active)return $('msg').textContent='Usuario no activo';me=data;$('login').classList.add('hide');$('app').classList.remove('hide');$('identity').textContent=(me.full_name||u.email)+' · '+me.role;if(!['RECEPCION','ADMIN'].includes(me.role)){$('navnew').classList.add('hide')}if(me.role==='ADMIN')$('navadmin').classList.remove('hide');await refresh();sb.channel('v2').on('postgres_changes',{event:'*',schema:'public',table:'shipments'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'incidents'},refresh).subscribe()}
async function refresh(){const [a,b,c]=await Promise.all([sb.from('shipments').select('*').order('requested_at',{ascending:false}),sb.from('events').select('*').order('created_at',{ascending:false}).limit(100),sb.from('incidents').select('*').order('created_at',{ascending:false})]);shipments=a.data||[];events=b.data||[];incs=c.data||[];metrics();render();renderIncidents()}
function metrics(){const today=new Date().toDateString();$('m1').textContent=shipments.filter(x=>x.status==='SOLICITADO').length;$('m2').textContent=shipments.filter(x=>['LOCALIZANDO','PREPARADO'].includes(x.status)).length;$('m3').textContent=shipments.filter(x=>x.status==='PENDIENTE_RECEPCION').length;$('m4').textContent=shipments.filter(x=>x.status==='EN_RECEPCION').length;$('m5').textContent=shipments.filter(x=>x.status==='ENTREGADO'&&new Date(x.delivered_at).toDateString()===today).length;$('recent').innerHTML=events.slice(0,10).map(e=>'<div><b>'+esc(e.event_type.replaceAll('_',' '))+'</b> · '+new Date(e.created_at).toLocaleString()+'<div class="muted">'+esc(e.detail)+'</div></div>').join('')||'<p class="muted">Todavía no hay movimientos.</p>'}
function render(){if(!$('rows'))return;const q=$('search').value.trim().toLowerCase(),st=$('statusfilter').value;const f=shipments.filter(s=>(!st||s.status===st)&&[s.tracking,s.customer_name,s.package_location,s.recipient_name,s.recipient_id,s.status,s.notes].some(v=>(v||'').toLowerCase().includes(q)));$('resultcount').textContent=f.length+' envío(s)';$('rows').innerHTML=f.map(s=>{let a='<button class="btn btn2" onclick="detail(\''+s.id+'\')">Ver</button>';if(['ESTACIONADOS','ADMIN'].includes(me.role)&&s.status==='SOLICITADO')a+='<button class="btn" onclick="setStatus(\''+s.id+'\',\'LOCALIZANDO\')">Localizando</button>';if(['ESTACIONADOS','ADMIN'].includes(me.role)&&s.status==='LOCALIZANDO')a+='<button class="btn" onclick="prepare(\''+s.id+'\')">Preparado</button>';if(['ESTACIONADOS','ADMIN'].includes(me.role)&&['PREPARADO','INCIDENCIA'].includes(s.status))a+='<button class="btn ok" onclick="handoff(\''+s.id+'\')">A Recepción</button>';if(['RECEPCION','ADMIN'].includes(me.role)&&s.status==='PENDIENTE_RECEPCION')a+='<button class="btn ok" onclick="confirmReception(\''+s.id+'\')">Confirmar</button>';if(['RECEPCION','ADMIN'].includes(me.role)&&s.status==='EN_RECEPCION')a+='<button class="btn ok" onclick="deliver(\''+s.id+'\')">Entregar</button>';if(s.status!=='ENTREGADO')a+='<button class="btn danger" onclick="incident(\''+s.id+'\')">Incidencia</button>';return '<tr class="rowclick"><td><b>'+esc(s.tracking)+'</b></td><td>'+esc(s.customer_name)+'</td><td>'+esc(s.package_location)+'</td><td><span class="tag '+(s.priority==='URGENTE'?'urgent':'')+'">'+esc(s.priority)+'</span></td><td><span class="tag">'+esc(labels[s.status]||s.status)+'</span></td><td><div class="actions">'+a+'</div></td></tr>'}).join('')}
async function ev(id,type,detail=''){await sb.from('events').insert({shipment_id:id,actor_id:me.id,event_type:type,detail})}
async function createShipment(){const o={tracking:$('tracking').value.trim(),customer_name:$('customer').value.trim(),package_location:$('location').value.trim(),notes:$('notes').value.trim(),priority:$('priority').value,requested_by:me.id};if(!o.tracking||!o.customer_name||!o.package_location)return alert('Completa envío, cliente y ubicación.');const {data,error}=await sb.from('shipments').insert(o).select().single();if(error)return alert(error.message);await ev(data.id,'SOLICITUD_CREADA','Solicitud registrada');['tracking','customer','location','notes'].forEach(x=>$(x).value='');await refresh();alert('Solicitud registrada.')}
async function createBulk(){const lines=$('bulk').value.split(/\n/).map(x=>x.trim()).filter(Boolean);if(!lines.length)return alert('Introduce solicitudes.');const rows=[];for(const line of lines){const p=line.split(';').map(x=>x.trim());if(p.length<3||!p[0]||!p[1]||!p[2])return alert('Formato incorrecto: '+line);rows.push({tracking:p[0],customer_name:p[1],package_location:p[2],notes:p.slice(3).join('; '),requested_by:me.id})}let batch=null;const title=$('batchtitle')?.value.trim()||'';const bnotes=$('batchnotes')?.value.trim()||'';if(title||lines.length>1){const code='LOTE-'+new Date().toISOString().replace(/[-:TZ.]/g,'').slice(0,14);const {data:b,error:be}=await sb.from('request_batches').insert({batch_code:code,title:title||code,notes:bnotes,created_by:me.id}).select().single();if(be)return alert(be.message);batch=b;rows.forEach(r=>r.batch_id=batch.id)}const {data,error}=await sb.from('shipments').insert(rows).select();if(error)return alert(error.message);for(const s of data)await ev(s.id,'SOLICITUD_CREADA',batch?'Registro múltiple · '+batch.batch_code:'Registro múltiple');$('bulk').value='';if($('batchtitle'))$('batchtitle').value='';if($('batchnotes'))$('batchnotes').value='';await refresh();alert(data.length+' solicitudes registradas'+(batch?' en '+batch.batch_code:'')+'.')}
async function setStatus(id,status){const {error}=await sb.from('shipments').update({status}).eq('id',id);if(error)return alert(error.message);await ev(id,status,'Cambio de estado');refresh()}
async function prepare(id){const {error}=await sb.from('shipments').update({status:'PREPARADO',prepared_by:me.id,prepared_at:now()}).eq('id',id);if(error)return alert(error.message);await ev(id,'PREPARADO','Envío preparado en Estacionados');refresh()}
async function handoff(id){if(!confirm('¿Confirmas la entrega física a Recepción?'))return;const {error}=await sb.from('shipments').update({status:'PENDIENTE_RECEPCION',warehouse_by:me.id,warehouse_at:now(),handoff_at:now()}).eq('id',id);if(error)return alert(error.message);await ev(id,'ENTREGADO_POR_ESTACIONADOS','Pendiente de confirmación de Recepción');refresh()}
async function confirmReception(id){if(!confirm('¿Recepción tiene físicamente el paquete?'))return;const {error}=await sb.from('shipments').update({status:'EN_RECEPCION',reception_by:me.id,reception_at:now(),reception_confirmed_at:now()}).eq('id',id);if(error)return alert(error.message);await ev(id,'RECIBIDO_EN_RECEPCION','Custodia confirmada');refresh()}
async function deliver(id){const n=prompt('Nombre de la persona que recoge:');if(!n)return;const dni=prompt('DNI/identificación (opcional):')||'';if(!confirm('Confirmar entrega a '+n))return;const {error}=await sb.from('shipments').update({status:'ENTREGADO',recipient_name:n,recipient_id:dni,delivered_by:me.id,delivered_at:now()}).eq('id',id);if(error)return alert(error.message);await ev(id,'ENTREGA_FINAL','Entregado a '+n+(dni?' · ID '+dni:''));refresh()}
async function incident(id){const d=prompt('Describe la incidencia:');if(!d)return;await sb.from('incidents').insert({shipment_id:id,actor_id:me.id,detail:d});await sb.from('shipments').update({status:'INCIDENCIA',incident_reason:d}).eq('id',id);await ev(id,'INCIDENCIA',d);refresh()}
function renderIncidents(){$('incidentlist').innerHTML=incs.filter(i=>!i.resolved).map(i=>{const s=shipments.find(x=>x.id===i.shipment_id);return '<div class="card"><b>'+esc(s?.tracking||'Envío')+'</b> · '+esc(s?.customer_name||'')+'<p>'+esc(i.detail)+'</p><span class="muted">'+new Date(i.created_at).toLocaleString()+'</span> <button class="btn ok" onclick="resolveIncident(\''+i.id+'\',\''+i.shipment_id+'\')">Resolver</button></div>'}).join('')||'<p class="muted">No hay incidencias abiertas.</p>'}
async function resolveIncident(iid,sid){await sb.from('incidents').update({resolved:true,resolved_at:now()}).eq('id',iid);await sb.from('shipments').update({status:'LOCALIZANDO',incident_reason:null}).eq('id',sid);await ev(sid,'INCIDENCIA_RESUELTA','Incidencia resuelta');refresh()}
async function detail(id){const s=shipments.find(x=>x.id===id);const {data:e}=await sb.from('events').select('*,profiles(full_name)').eq('shipment_id',id).order('created_at');$('detail').classList.remove('hide');$('detail').innerHTML='<h2>Expediente '+esc(s.tracking)+'</h2><div class="grid"><div><b>Cliente</b><br>'+esc(s.customer_name)+'</div><div><b>Ubicación</b><br>'+esc(s.package_location)+'</div><div><b>Estado</b><br>'+esc(labels[s.status])+'</div><div><b>Prioridad</b><br>'+esc(s.priority)+'</div></div><p><b>Observaciones:</b> '+esc(s.notes||'—')+'</p>'+(s.recipient_name?'<p><b>Recogido por:</b> '+esc(s.recipient_name)+' '+esc(s.recipient_id||'')+'</p>':'')+'<h3>Trazabilidad</h3><div class="timeline">'+(e||[]).map(x=>'<div><b>'+esc(x.event_type.replaceAll('_',' '))+'</b><br><span class="muted">'+new Date(x.created_at).toLocaleString()+' · '+esc(x.profiles?.full_name||'Usuario')+'</span><br>'+esc(x.detail)+'</div>').join('')+'</div>';go('shipments');$('detail').scrollIntoView({behavior:'smooth'})}
function exportCSV(){const h=['Envio','Cliente','Ubicacion','Prioridad','Estado','Solicitado','Entregado','Recogido por','Identificacion'];const rows=shipments.map(s=>[s.tracking,s.customer_name,s.package_location,s.priority,s.status,s.requested_at,s.delivered_at||'',s.recipient_name||'',s.recipient_id||'']);const csv=[h,...rows].map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='envios_'+new Date().toISOString().slice(0,10)+'.csv';a.click()}
async function adminCall(body){const {data:{session}}=await sb.auth.getSession();const r=await fetch(SB_URL+'/functions/v1/admin-users',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token,'apikey':SB_KEY},body:JSON.stringify(body)});return r.json()}
async function createUser(){const b={action:'create',full_name:$('ufull').value.trim(),email:$('uemail').value.trim(),password:$('upass').value,role:$('urole').value};if(!b.full_name||!b.email||b.password.length<8)return alert('Completa los datos. Contraseña mínima: 8 caracteres.');const x=await adminCall(b);if(x.error)return alert(x.error);$('ufull').value=$('uemail').value=$('upass').value='';loadUsers();alert('Usuario creado.')}
async function loadUsers(){if(me?.role!=='ADMIN')return;const x=await adminCall({action:'list'});if(x.error)return;$('users').innerHTML='<div class="tablewrap"><table><tr><th>Nombre</th><th>Rol</th><th>Activo</th></tr>'+x.data.map(u=>'<tr><td>'+esc(u.full_name)+'</td><td>'+esc(u.role)+'</td><td>'+(u.active?'Sí':'No')+'</td></tr>').join('')+'</table></div>'}
async function changePassword(){const p=$('newpass').value;if(p.length<8)return alert('Mínimo 8 caracteres.');const {error}=await sb.auth.updateUser({password:p});alert(error?error.message:'Contraseña cambiada.');$('newpass').value=''}
async function logout(){await sb.auth.signOut();location.reload()}sb.auth.getSession().then(({data})=>{if(data.session)loadApp(data.session.user)});