import {PGlite} from '@electric-sql/pglite';
import {pgcrypto} from '@electric-sql/pglite/contrib/pgcrypto';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite({extensions:{pgcrypto}});
await db.exec(`create role anon;create role authenticated;
create schema auth;create schema private;create schema storage;create schema extensions;
create extension pgcrypto with schema extensions;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table public.profiles(id uuid primary key, role text, active boolean);
create table public.shipments (id uuid primary key,tracking text,customer_name text,package_location text,status text,notes text,requested_by uuid,requested_at timestamptz,warehouse_by uuid,warehouse_at timestamptz,reception_by uuid,reception_at timestamptz,recipient_name text,recipient_id text,delivered_by uuid,delivered_at timestamptz,proof_path text,updated_at timestamptz,handoff_at timestamptz,reception_confirmed_at timestamptz,priority text,prepared_by uuid,prepared_at timestamptz,incident_reason text,batch_id uuid,location_zone text,location_shelf text,location_slot text,previous_status text,corrected_at timestamptz,corrected_by uuid,correction_reason text,archived boolean,proof_name text,proof_uploaded_at timestamptz,delivery_signature text,delivery_signature_at timestamptz,delivery_notes text,external_reference text,stock_import_id uuid,stock_snapshot jsonb,archive_reason text);
create table events(id bigint generated always as identity,shipment_id uuid,actor_id uuid,event_type text,detail text,created_at timestamptz default now());
create table incidents(shipment_id uuid,actor_id uuid,detail text,resolved boolean,resolved_at timestamptz);
create table shipment_proofs(shipment_id uuid,uploaded_by uuid,uploaded_at timestamptz);
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(bucket_id text,name text,owner_id text,metadata jsonb);
alter table storage.objects enable row level security;
grant usage on schema public,auth,storage to authenticated;
grant select on profiles,shipments to authenticated;
grant select,insert on storage.objects to authenticated;
insert into profiles values ('00000000-0000-4000-8000-000000000001','RECEPCION',true),('00000000-0000-4000-8000-000000000002','ESTACIONADOS',true),('00000000-0000-4000-8000-000000000003','ADMIN',false);
insert into shipments(id,status,updated_at) values('10000000-0000-4000-8000-000000000001','EN_RECEPCION','2026-09-26T10:00:00Z');`);
await db.exec(await readFile(new URL('./existing-triggers.sql',import.meta.url),'utf8'));
await db.exec(`create trigger enforce_shipment_update_security before update on shipments for each row execute function enforce_shipment_update_security();create trigger audit_shipments after update on shipments for each row execute function audit_shipment_change();`);
await db.exec(await readFile(new URL('../migrations/20260926_secure_delivery.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../migrations/20260926_delivery_audit_types.sql',import.meta.url),'utf8'));
await db.exec('create trigger validate_event_insert before insert on events for each row execute function validate_event_insert()');
let count=0;
const id='10000000-0000-4000-8000-000000000001', path=id+'/test.webp',stamp='2026-09-26T10:00:00Z';
const identity=async n=>db.query("select set_config('request.jwt.claim.sub',$1,false)",[n?`00000000-0000-4000-8000-00000000000${n}`:'']);
const delivery=(time=stamp,p=path)=>db.query('select complete_delivery_secure($1,$2,$3,$4,$5)',[id,'Prueba controlada','TEST-12345',p,time]);
async function check(name,fn){await fn();count++;console.log('PASS '+name)}
await check('anonymous cannot deliver',async()=>{await identity(null);await assert.rejects(delivery,/no autorizada/)});
await check('warehouse cannot deliver',async()=>{await identity(2);await assert.rejects(delivery,/no autorizada/)});
await check('inactive admin cannot deliver',async()=>{await identity(3);await assert.rejects(delivery,/no autorizada/)});
await identity(1);
await check('missing signature rejected',()=>assert.rejects(delivery,/firma no existe/));
await check('direct update cannot bypass signature',()=>assert.rejects(db.query("update shipments set status='ENTREGADO',recipient_name='Prueba' where id=$1",[id]),/requiere firma/));
await db.query("insert into storage.objects values('signatures',$1,auth.uid(),'{\"mimetype\":\"image/webp\",\"size\":3000}')",[path]);
await check('stale version rejected',()=>assert.rejects(delivery('2026-09-25T10:00:00Z'),/ha cambiado/));
await check('other shipment path rejected',()=>assert.rejects(delivery(stamp,'other/test.webp'),/firma no existe/));
await check('delivery succeeds with existing state and audit triggers',async()=>assert.equal((await delivery()).rows[0].complete_delivery_secure.ok,true));
await check('DNI encrypted and excluded from shipment and audit',async()=>{
 assert.equal((await db.query('select recipient_id from shipments where id=$1',[id])).rows[0].recipient_id,null);
 const r=await db.query("select encrypted_dni,extensions.pgp_sym_decrypt(encrypted_dni,key_value) as original from private.delivery_identity cross join private.delivery_key");assert.equal(r.rows[0].original,'TEST-12345');assert.ok(r.rows[0].encrypted_dni.length>32);
 assert.equal((await db.query("select count(*)::int n from events where detail like '%TEST-12345%'")).rows[0].n,0);
});
await check('retry is idempotent',async()=>{assert.equal((await delivery()).rows[0].complete_delivery_secure.already_saved,true);assert.equal((await db.query('select count(*)::int n from delivery_signatures')).rows[0].n,1)});
await check('authorized single DNI lookup logged',async()=>{assert.equal((await db.query('select get_delivery_identity($1) dni',[id])).rows[0].dni,'TEST-12345');assert.equal((await db.query("select count(*)::int n from events where event_type='IDENTIFICACION_CONSULTADA'")).rows[0].n,1)});
await check('private ciphertext inaccessible to authenticated role',async()=>{await db.exec('set role authenticated');await assert.rejects(db.query('select * from private.delivery_identity'),/permission denied/);await db.exec('reset role')});
await check('warehouse cannot view signature or DNI',async()=>{await identity(2);await db.exec('set role authenticated');assert.equal((await db.query('select * from delivery_signatures')).rows.length,0);assert.equal((await db.query('select * from storage.objects')).rows.length,0);await assert.rejects(db.query('select get_delivery_identity($1)',[id]),/no autorizado/);await db.exec('reset role')});
await check('reception can view linked private signature',async()=>{await identity(1);await db.exec('set role authenticated');assert.equal((await db.query('select * from delivery_signatures')).rows.length,1);assert.equal((await db.query('select * from storage.objects')).rows.length,1);await db.exec('reset role')});
await check('non-admin cannot read capacity',()=>assert.rejects(db.query('select get_capacity_status()'),/no autorizado/));
await db.close();console.log(`${count} security tests passed`);

